networks:
  my-network:
    driver: bridge

services:
  db:
    container_name: sde3-database
    image: postgres
    ports:
      - "${DB_PORT_HOST}:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./database/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - my-network
  proxy:
    container_name: sde3-proxy
    build:
      context: ./proxy
      args:
        - PORT=${PROXY_PORT}
    environment:
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
    networks:
      - my-network
